const languages=['tr','en','de','zh','hi','es','fr','ar','pt','ru'];
const bi=(tr,en)=>Object.fromEntries(languages.map(code=>[code,code==='tr'?tr:en]));
const common={back:bi('← Oyuna dön','← Back to game'),footer:bi('© 2026 CodExa. Tüm hakları saklıdır.','© 2026 CodExa. All rights reserved.')};
const docs={
privacy:{
 title:bi('Gizlilik Politikası','Privacy Policy'),updated:bi('Son güncelleme: 16 Ağustos 2026','Last updated: August 16, 2026'),intro:bi('Bu politika, CodExa tarafından sunulan Magnetic Maze Android oyununun bilgileri nasıl işlediğini açıklar.','This policy explains how the Magnetic Maze Android game provided by CodExa handles information.'),
 h1:bi('1. Cihazda saklanan oyun verileri','1. Game data stored on device'),p1:bi('Bölüm ilerlemesi, yıldız kayıtları, dil ve erişilebilirlik ayarları yalnızca cihazınızda saklanır. Mevcut sürüm hesap oluşturmaz ve bu verileri CodExa sunucularına yüklemez. Uygulamayı kaldırmak veya uygulama verilerini temizlemek ilerlemeyi silebilir.','Level progress, star records, language, and accessibility settings are stored only on your device. The current version creates no account and does not upload this data to CodExa servers. Uninstalling the app or clearing its data may erase progress.'),
 h2:bi('2. Reklamlar ve rıza','2. Advertising and consent'),p2:bi('Oyun, Google Mobile Ads (AdMob) üzerinden bölüm geçişlerinde geçiş reklamları ve yalnızca oyuncu seçtiğinde ipucu karşılığı ödüllü reklamlar sunar. Banner reklam kullanılmaz. Google; reklam kimliği, cihaz bilgisi, yaklaşık konum, reklam etkileşimleri ve tanılama verilerini reklam sunumu, ölçüm, güvenlik ve dolandırıcılığı önleme amaçlarıyla işleyebilir. Gereken bölgelerde Google User Messaging Platform üzerinden gizlilik seçenekleri sunulur.','The game uses Google Mobile Ads (AdMob) for interstitial ads at natural level breaks and optional rewarded ads chosen by the player in exchange for a hint. No banner ads are used. Google may process advertising identifiers, device information, approximate location, ad interactions, and diagnostics for ad delivery, measurement, security, and fraud prevention. Privacy choices are offered through Google User Messaging Platform where required.'),
 h3:bi('3. İzinler ve üçüncü taraflar','3. Permissions and third parties'),p3:bi('Reklamların yüklenmesi için internet erişimi gerekir; oyun reklam bulunmadığında çevrimdışı oynanabilir. Google veri uygulamaları hakkında ayrıntı için Google Gizlilik Politikası’nı inceleyebilirsiniz: <a href="https://policies.google.com/privacy">policies.google.com/privacy</a>.','Internet access is required to load ads; gameplay remains available offline when ads are unavailable. For details about Google data practices, see the <a href="https://policies.google.com/privacy">Google Privacy Policy</a>.'),
 h4:bi('4. Çocukların gizliliği','4. Children’s privacy'),p4:bi('CodExa, çocuklardan bilerek doğrudan kişisel bilgi istemez. Bir çocuğun kişisel bilgilerini bize gönderdiğini düşünüyorsanız silme talebi için iletişime geçin. Ebeveynler cihaz ve reklam gizliliği ayarlarını yönetebilir.','CodExa does not knowingly request personal information directly from children. If you believe a child sent personal information to us, contact us to request deletion. Parents can manage device and advertising privacy settings.'),
 h5:bi('5. Haklarınız ve iletişim','5. Your rights and contact'),p5:bi('Gizlilik soruları, erişim veya silme talepleri için <a href="mailto:exaque2@gmail.com?subject=Magnetic%20Maze%20Gizlilik">exaque2@gmail.com</a> adresine yazabilirsiniz. Politika değişirse güncel tarih bu sayfada yayımlanır.','For privacy questions, access, or deletion requests, email <a href="mailto:exaque2@gmail.com?subject=Magnetic%20Maze%20Privacy">exaque2@gmail.com</a>. If this policy changes, the updated date will be published here.')},
terms:{
 title:bi('Kullanım Koşulları','Terms of Use'),updated:bi('Yürürlük tarihi: 16 Ağustos 2026','Effective: August 16, 2026'),intro:bi('Magnetic Maze’i indirerek veya kullanarak bu koşulları kabul edersiniz.','By downloading or using Magnetic Maze, you agree to these terms.'),
 h1:bi('1. Kullanım lisansı','1. License to use'),p1:bi('CodExa size oyunu kişisel ve ticari olmayan amaçlarla kullanmanız için sınırlı, geri alınabilir ve devredilemez bir lisans verir. Oyunu tersine mühendislik, yetkisiz dağıtım veya hizmetleri bozma amacıyla kullanamazsınız.','CodExa grants you a limited, revocable, non-transferable license to use the game for personal, non-commercial purposes. You may not reverse engineer, redistribute without authorization, or use it to disrupt services.'),
 h2:bi('2. Oyun ve reklamlar','2. Gameplay and advertising'),p2:bi('Oyun çevrimdışı oynanabilir. Reklam kullanılabilirliği garanti edilmez. Ödüllü ipucu yalnızca reklam sağlayıcısı tamamlanmış ödülü doğruladığında verilir. Sanal ilerlemenin parasal değeri yoktur.','The game can be played offline. Ad availability is not guaranteed. A rewarded hint is granted only when the ad provider confirms completion. Virtual progress has no monetary value.'),
 h3:bi('3. Sorumluluk sınırı','3. Limitation of liability'),p3:bi('Oyun uygulanabilir hukukun izin verdiği ölçüde “olduğu gibi” sunulur. CodExa kesintisiz çalışma veya her cihazla uyumluluk garantisi vermez.','The game is provided “as is” to the extent permitted by applicable law. CodExa does not guarantee uninterrupted operation or compatibility with every device.'),
 h4:bi('4. Değişiklikler ve iletişim','4. Changes and contact'),p4:bi('Oyun ve bu koşullar zamanla güncellenebilir. Sorularınız için <a href="mailto:exaque2@gmail.com?subject=Magnetic%20Maze">exaque2@gmail.com</a> adresine yazabilirsiniz.','The game and these terms may be updated over time. Questions may be sent to <a href="mailto:exaque2@gmail.com?subject=Magnetic%20Maze">exaque2@gmail.com</a>.')},
support:{
 title:bi('Destek ve İletişim','Support and Contact'),updated:bi('Magnetic Maze yardım merkezi','Magnetic Maze help center'),intro:bi('Bir sorun mu yaşadınız veya fikriniz mi var? Aşağıdaki çözümleri deneyin ya da bize e-posta gönderin.','Having an issue or an idea? Try the solutions below or email us.'),
 h1:bi('1. Oyun açılmıyor veya takılıyor','1. The game will not open or freezes'),p1:bi('Oyunu yeniden açın, cihazı yeniden başlatın ve Google Play’den en güncel sürümü kullandığınızı kontrol edin.','Reopen the game, restart your device, and confirm that you use the latest Google Play version.'),
 h2:bi('2. İlerlemem kayboldu','2. My progress is gone'),p2:bi('İlerleme yalnızca cihazda saklanır. Uygulamayı kaldırmak veya uygulama verilerini temizlemek kayıtları silebilir; mevcut sürümde bulut geri yükleme yoktur.','Progress is stored only on your device. Uninstalling or clearing app data may erase it; cloud restore is not available in the current version.'),
 h3:bi('3. Reklam veya ipucu çalışmadı','3. An ad or hint did not work'),p3:bi('İnternet bağlantınızı kontrol edip daha sonra yeniden deneyin. Reklam tamamlanmadan kapatılırsa ipucu verilmeyebilir. Reklam bulunmaması oyunu oynamanızı engellemez.','Check your internet connection and try again later. A hint may not be granted if the ad is closed before completion. Unavailable ads do not prevent gameplay.'),
 h4:bi('4. Bize ulaşın','4. Contact us'),p4:bi('E-posta: <a href="mailto:exaque2@gmail.com?subject=Magnetic%20Maze%20Destek">exaque2@gmail.com</a>. Cihaz modeli, Android sürümü, oyun sürümü ve sorunu yeniden oluşturma adımlarını ekleyin.','Email: <a href="mailto:exaque2@gmail.com?subject=Magnetic%20Maze%20Support">exaque2@gmail.com</a>. Include device model, Android version, game version, and reproduction steps.')}
};
const page=document.documentElement.dataset.page;const d=docs[page];window.PAGE_TRANSLATIONS={...common,page_title:d.title};
const order=['h1','p1','h2','p2','h3','p3','h4','p4','h5','p5'];const main=document.getElementById('document');main.innerHTML=`<div class="eyebrow">Magnetic Maze · CodExa</div><h1 data-i18n="doc_title">${d.title.tr}</h1><div class="status" data-i18n="updated">${d.updated.tr}</div><p class="notice" data-i18n="intro">${d.intro.tr}</p>`+order.filter(k=>d[k]).map(k=>k[0]==='h'?`<h2 data-i18n="${k}">${d[k].tr}</h2>`:`<p data-i18n="${k}">${d[k].tr}</p>`).join('');window.PAGE_TRANSLATIONS.doc_title=d.title;window.PAGE_TRANSLATIONS.updated=d.updated;window.PAGE_TRANSLATIONS.intro=d.intro;order.forEach(k=>{if(d[k])window.PAGE_TRANSLATIONS[k]=d[k]});
